### ISSUE TITLE
Release v0.7.0

### ISSUE THREAD

**Issue by cbm755** [catch22/octave-doctest#192]
@catch22 maybe we should think about release b/c of the Makefile bug you found...

### TODO list
- [x] resolve #117 and #183 
- [x] ~~#181 would be nice to have but maybe not essential?~~
- [x] test on Matlab
- [x] test on new Octave 5.1
- [x] double-check what Octave versions we're running on CI these days...
- [x] resolve all milestone 0.7.0 issues/PRs
- [x] Update `NEWS`
- [x] Update `DESCRIPTION`
- [x] ~~Tag git commit once accepted upstream~~  [this isn't done by us]
- [x] After release, push tags to github
- [x] Do github release.

This is not 1.0 b/c of e.g., #181, testing mex files, manual, bikeshedding `doctest_collect`, etc.

**Comment by catch22** [comment]
👍

**Comment by mtmiller** [comment]
Just noting that #189 doesn't affect users or `pkg install`, it's only the maintainer Makefile `install` rule for development that is affected.

**Comment by cbm755** [comment]
Filed upstream at https://sourceforge.net/p/octave/package-releases/373/

Octave Forge releases are back logged, I've been trying to help by reviewing other release candidates but more help is always needed.

**Comment by catch22** [comment]
I added three todo items above.

**Comment by cbm755** [comment]
Was there something wrong with NEWS and DESCRIPTION?  Should I check those off the list?   (I tried to follow the release process on the wiki)

**Comment by catch22** [comment]
Gah, I think I looked at an old checkout when grepping for Version and seeing 0.6. Very sorry about that..
